// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/Lexer.flex


package main.jflex;

import main.java.ClaseLexica;
import main.java.Token;


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\1\1\1\2\1\3\1\4\2\5\22\0\1\6"+
    "\1\7\1\10\2\1\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\12\24\1\25"+
    "\1\26\1\27\1\30\1\31\2\1\3\32\1\33\1\34"+
    "\1\35\24\32\1\36\1\37\1\40\1\0\1\41\1\0"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\32\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\32\1\61\1\62\1\63\1\64\1\65\1\66\1\67"+
    "\2\32\1\70\1\71\1\72\7\0\1\4\73\0\1\32"+
    "\7\0\1\32\3\0\1\32\3\0\1\32\1\0\1\32"+
    "\2\0\1\32\3\0\1\32\1\0\1\32\4\0\1\32"+
    "\7\0\1\32\3\0\1\32\3\0\1\32\1\0\1\32"+
    "\2\0\1\32\3\0\1\32\1\0\1\32\u012b\0\2\4"+
    "\326\0\u0100\4";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\0\1\3\2\0\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\14\22"+
    "\1\25\1\0\1\26\1\27\1\30\1\0\1\31\2\0"+
    "\1\32\1\0\1\33\1\0\1\34\1\35\1\36\1\37"+
    "\4\22\1\40\4\22\1\41\13\22\1\42\1\43\1\0"+
    "\1\44\1\34\1\0\1\34\11\22\1\45\2\22\1\46"+
    "\10\22\1\0\1\47\1\0\1\34\1\33\1\0\1\34"+
    "\1\22\1\50\3\22\1\51\2\22\1\52\4\22\1\53"+
    "\1\54\3\22\1\55\1\56\1\22\1\0\1\34\1\0"+
    "\1\34\1\57\3\22\1\60\1\61\1\62\1\22\1\63"+
    "\4\22\1\64\1\0\1\34\2\22\1\65\1\22\1\66"+
    "\1\67\1\70\1\71\1\0\1\34\1\72\1\73\1\22"+
    "\3\0\1\74\1\34\1\75\3\0\1\34\1\0\1\33"+
    "\1\0\1\33\2\0\1\33\1\0\1\33\1\0\1\33"+
    "\1\0\1\33\2\0\1\33\3\0\1\33\1\0\1\33"+
    "\1\0\1\33\4\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[201];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\354"+
    "\0\354\0\354\0\354\0\354\0\354\0\354\0\u019d\0\u01d8"+
    "\0\354\0\354\0\u0213\0\u024e\0\u0289\0\u02c4\0\354\0\354"+
    "\0\u02ff\0\u033a\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461\0\u049c"+
    "\0\u04d7\0\u0512\0\u054d\0\u0588\0\354\0\u05c3\0\354\0\354"+
    "\0\354\0\u05fe\0\354\0\u0639\0\u0674\0\u06af\0\u06ea\0\354"+
    "\0\u0725\0\354\0\354\0\354\0\354\0\u0760\0\u079b\0\u07d6"+
    "\0\u0811\0\u084c\0\u0887\0\u08c2\0\u08fd\0\u0938\0\u02c4\0\u0973"+
    "\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b"+
    "\0\u0b86\0\u0bc1\0\354\0\354\0\u0bfc\0\u0c37\0\u0c72\0\u0cad"+
    "\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a\0\u0e85"+
    "\0\u0ec0\0\u0efb\0\u02c4\0\u0f36\0\u0f71\0\u02c4\0\u0fac\0\u0fe7"+
    "\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\354"+
    "\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u1235\0\u12ab\0\u02c4\0\u12e6"+
    "\0\u1321\0\u135c\0\u02c4\0\u1397\0\u13d2\0\u02c4\0\u140d\0\u1448"+
    "\0\u1483\0\u14be\0\u02c4\0\u02c4\0\u14f9\0\u1534\0\u156f\0\u02c4"+
    "\0\u02c4\0\u15aa\0\u15e5\0\u1620\0\u165b\0\u1696\0\u02c4\0\u16d1"+
    "\0\u170c\0\u1747\0\u02c4\0\u02c4\0\u02c4\0\u1782\0\u02c4\0\u17bd"+
    "\0\u17f8\0\u1833\0\u186e\0\u02c4\0\u18a9\0\u18e4\0\u191f\0\u195a"+
    "\0\u02c4\0\u1995\0\u02c4\0\u02c4\0\u02c4\0\u02c4\0\u19d0\0\u1a0b"+
    "\0\u02c4\0\u02c4\0\u1a46\0\u1a81\0\u1abc\0\u1af7\0\354\0\u1b32"+
    "\0\u02c4\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e\0\u1c59\0\u1c94\0\u1ccf"+
    "\0\u1d0a\0\u1d45\0\u1d80\0\u1dbb\0\u1df6\0\u1e31\0\u1e6c\0\u1ea7"+
    "\0\u1ee2\0\u1f1d\0\u1f58\0\u1f93\0\u1fce\0\u2009\0\u2044\0\u207f"+
    "\0\u20ba\0\u20f5\0\u2130\0\u216b\0\u21a6\0\u21e1\0\u221c\0\u2257"+
    "\0\u2292";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[201];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\0\2\2\1\0\2\2\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\4\26"+
    "\1\27\1\0\1\30\2\26\1\31\1\32\1\33\1\34"+
    "\1\35\2\26\1\36\5\26\1\37\1\40\1\41\1\42"+
    "\1\26\1\43\1\44\1\26\1\45\1\46\1\47\2\0"+
    "\2\2\1\0\2\2\114\0\1\50\42\0\10\4\1\51"+
    "\26\4\1\52\33\4\105\0\1\53\61\0\2\54\4\0"+
    "\1\54\1\0\2\54\17\0\4\54\1\0\1\54\2\0"+
    "\26\54\1\0\1\54\17\0\1\55\4\0\1\56\71\0"+
    "\1\57\1\0\1\20\6\0\1\60\1\61\1\62\7\0"+
    "\1\60\1\61\1\62\53\0\1\63\72\0\1\64\72\0"+
    "\1\65\66\0\1\26\5\0\4\26\3\0\27\26\27\0"+
    "\1\26\5\0\4\26\3\0\20\26\1\66\6\26\27\0"+
    "\1\26\5\0\4\26\3\0\1\26\1\67\14\26\1\70"+
    "\10\26\27\0\1\26\5\0\4\26\3\0\5\26\1\71"+
    "\10\26\1\72\10\26\27\0\1\26\5\0\4\26\3\0"+
    "\13\26\1\73\13\26\27\0\1\26\5\0\4\26\3\0"+
    "\1\26\1\74\11\26\1\75\7\26\1\76\3\26\27\0"+
    "\1\26\5\0\4\26\3\0\6\26\1\77\6\26\1\100"+
    "\11\26\27\0\1\26\5\0\4\26\3\0\20\26\1\101"+
    "\1\26\1\102\4\26\27\0\1\26\5\0\4\26\3\0"+
    "\5\26\1\103\15\26\1\104\3\26\27\0\1\26\5\0"+
    "\4\26\3\0\3\26\1\105\16\26\1\106\2\26\1\107"+
    "\1\26\27\0\1\26\5\0\4\26\3\0\20\26\1\110"+
    "\6\26\27\0\1\26\5\0\4\26\3\0\16\26\1\111"+
    "\10\26\27\0\1\26\5\0\4\26\3\0\10\26\1\112"+
    "\16\26\74\0\1\113\1\0\3\4\3\0\65\4\13\0"+
    "\1\114\57\0\16\55\1\115\54\55\23\0\1\116\73\0"+
    "\1\117\65\0\1\120\1\0\1\120\2\0\1\121\72\0"+
    "\1\26\5\0\4\26\3\0\5\26\1\122\21\26\27\0"+
    "\1\26\5\0\4\26\3\0\21\26\1\123\5\26\27\0"+
    "\1\26\5\0\4\26\3\0\14\26\1\124\12\26\27\0"+
    "\1\26\5\0\4\26\3\0\6\26\1\125\20\26\27\0"+
    "\1\26\5\0\4\26\3\0\23\26\1\126\3\26\27\0"+
    "\1\26\5\0\4\26\3\0\21\26\1\127\5\26\27\0"+
    "\1\26\5\0\4\26\3\0\13\26\1\130\13\26\27\0"+
    "\1\26\5\0\4\26\3\0\16\26\1\131\10\26\27\0"+
    "\1\26\5\0\4\26\3\0\15\26\1\132\11\26\27\0"+
    "\1\26\5\0\4\26\3\0\22\26\1\133\4\26\27\0"+
    "\1\26\5\0\4\26\3\0\11\26\1\134\4\26\1\135"+
    "\10\26\27\0\1\26\5\0\4\26\3\0\20\26\1\136"+
    "\6\26\27\0\1\26\5\0\4\26\3\0\22\26\1\137"+
    "\4\26\27\0\1\26\5\0\4\26\3\0\15\26\1\140"+
    "\11\26\27\0\1\26\5\0\4\26\3\0\1\26\1\141"+
    "\25\26\27\0\1\26\5\0\4\26\3\0\20\26\1\142"+
    "\6\26\27\0\1\26\5\0\4\26\3\0\11\26\1\143"+
    "\15\26\27\0\1\26\5\0\4\26\3\0\23\26\1\144"+
    "\3\26\27\0\1\26\5\0\4\26\3\0\11\26\1\145"+
    "\15\26\27\0\1\26\5\0\4\26\3\0\11\26\1\146"+
    "\15\26\3\0\16\147\1\115\4\147\1\150\47\147\3\116"+
    "\1\0\67\116\17\0\1\151\1\0\1\151\2\0\1\152"+
    "\6\0\1\153\1\154\1\155\7\0\1\153\1\154\1\155"+
    "\47\0\1\121\72\0\1\121\6\0\1\60\1\0\1\62"+
    "\7\0\1\60\1\0\1\62\47\0\1\26\5\0\4\26"+
    "\3\0\1\26\1\156\25\26\27\0\1\26\5\0\4\26"+
    "\3\0\5\26\1\157\21\26\27\0\1\26\5\0\4\26"+
    "\3\0\17\26\1\160\7\26\27\0\1\26\5\0\4\26"+
    "\3\0\1\26\1\161\25\26\27\0\1\26\5\0\4\26"+
    "\3\0\2\26\1\162\24\26\27\0\1\26\5\0\4\26"+
    "\3\0\5\26\1\163\21\26\27\0\1\26\5\0\4\26"+
    "\3\0\21\26\1\164\5\26\27\0\1\26\5\0\4\26"+
    "\3\0\1\26\1\165\25\26\27\0\1\26\5\0\4\26"+
    "\3\0\3\26\1\166\23\26\27\0\1\26\5\0\4\26"+
    "\3\0\15\26\1\167\11\26\27\0\1\26\5\0\4\26"+
    "\3\0\7\26\1\170\12\26\1\171\4\26\27\0\1\26"+
    "\5\0\4\26\3\0\23\26\1\172\3\26\27\0\1\26"+
    "\5\0\4\26\3\0\5\26\1\173\21\26\27\0\1\26"+
    "\5\0\4\26\3\0\15\26\1\174\11\26\27\0\1\26"+
    "\5\0\4\26\3\0\11\26\1\175\11\26\1\176\3\26"+
    "\27\0\1\26\5\0\4\26\3\0\22\26\1\177\4\26"+
    "\27\0\1\26\5\0\4\26\3\0\5\26\1\200\21\26"+
    "\27\0\1\26\5\0\4\26\3\0\4\26\1\201\22\26"+
    "\27\0\1\26\5\0\4\26\3\0\13\26\1\202\13\26"+
    "\3\0\16\147\1\115\4\147\1\0\47\147\24\0\1\203"+
    "\65\0\1\151\1\0\1\151\2\0\1\204\6\0\1\153"+
    "\1\154\1\155\7\0\1\153\1\154\1\155\42\0\1\151"+
    "\1\0\1\151\70\0\1\205\1\0\1\205\2\0\1\206"+
    "\72\0\1\26\5\0\4\26\3\0\12\26\1\207\14\26"+
    "\27\0\1\26\5\0\4\26\3\0\13\26\1\210\13\26"+
    "\27\0\1\26\5\0\4\26\3\0\23\26\1\211\3\26"+
    "\27\0\1\26\5\0\4\26\3\0\13\26\1\212\13\26"+
    "\27\0\1\26\5\0\4\26\3\0\5\26\1\213\21\26"+
    "\27\0\1\26\5\0\4\26\3\0\22\26\1\214\4\26"+
    "\27\0\1\26\5\0\4\26\3\0\22\26\1\215\4\26"+
    "\27\0\1\26\5\0\4\26\3\0\20\26\1\216\6\26"+
    "\27\0\1\26\5\0\4\26\3\0\16\26\1\217\10\26"+
    "\27\0\1\26\5\0\4\26\3\0\20\26\1\220\6\26"+
    "\27\0\1\26\5\0\4\26\3\0\15\26\1\221\11\26"+
    "\27\0\1\26\5\0\4\26\3\0\3\26\1\222\23\26"+
    "\27\0\1\26\5\0\4\26\3\0\3\26\1\223\23\26"+
    "\27\0\1\26\5\0\4\26\3\0\5\26\1\224\21\26"+
    "\25\0\1\225\1\0\1\203\65\0\1\151\1\0\1\151"+
    "\2\0\1\226\6\0\1\153\1\154\1\155\7\0\1\153"+
    "\1\154\1\155\47\0\1\206\65\0\1\151\1\0\1\151"+
    "\2\0\1\206\6\0\1\153\1\0\1\155\7\0\1\153"+
    "\1\0\1\155\47\0\1\26\5\0\4\26\3\0\5\26"+
    "\1\227\21\26\27\0\1\26\5\0\4\26\3\0\13\26"+
    "\1\230\13\26\27\0\1\26\5\0\4\26\3\0\5\26"+
    "\1\231\21\26\27\0\1\26\5\0\4\26\3\0\1\26"+
    "\1\232\25\26\27\0\1\26\5\0\4\26\3\0\15\26"+
    "\1\233\11\26\27\0\1\26\5\0\4\26\3\0\7\26"+
    "\1\234\17\26\27\0\1\26\5\0\4\26\3\0\22\26"+
    "\1\235\4\26\27\0\1\26\5\0\4\26\3\0\10\26"+
    "\1\236\16\26\27\0\1\237\65\0\1\151\1\0\1\151"+
    "\2\0\1\240\6\0\1\153\1\154\1\155\7\0\1\153"+
    "\1\154\1\155\47\0\1\26\5\0\4\26\3\0\26\26"+
    "\1\241\27\0\1\26\5\0\4\26\3\0\22\26\1\242"+
    "\4\26\27\0\1\26\5\0\4\26\3\0\14\26\1\243"+
    "\12\26\27\0\1\244\6\0\1\245\1\246\1\245\7\0"+
    "\1\245\1\246\1\245\2\0\1\247\37\0\1\151\1\0"+
    "\1\151\2\0\1\250\6\0\1\153\1\154\1\155\7\0"+
    "\1\153\1\154\1\155\47\0\1\26\5\0\4\26\3\0"+
    "\1\26\1\251\25\26\27\0\1\252\6\0\1\245\1\246"+
    "\1\245\7\0\1\245\1\246\1\245\2\0\1\247\72\0"+
    "\1\247\37\0\1\253\1\0\1\253\2\0\1\254\65\0"+
    "\1\151\1\0\1\151\2\0\1\255\6\0\1\153\1\154"+
    "\1\155\7\0\1\153\1\154\1\155\47\0\1\256\6\0"+
    "\1\245\1\246\1\245\7\0\1\245\1\246\1\245\2\0"+
    "\1\247\44\0\1\254\72\0\1\254\6\0\1\245\1\0"+
    "\1\245\7\0\1\245\1\0\1\245\2\0\1\247\37\0"+
    "\1\151\1\0\1\151\2\0\1\257\6\0\1\153\1\154"+
    "\1\155\7\0\1\153\1\154\1\155\47\0\1\260\6\0"+
    "\1\245\1\246\1\245\7\0\1\245\1\246\1\245\2\0"+
    "\1\247\37\0\1\151\1\0\1\151\2\0\1\261\6\0"+
    "\1\153\1\262\10\0\1\153\1\262\50\0\1\263\6\0"+
    "\1\245\1\246\1\245\7\0\1\245\1\246\1\245\2\0"+
    "\1\247\37\0\1\151\1\0\1\151\2\0\1\264\6\0"+
    "\1\153\1\262\10\0\1\153\1\262\43\0\1\265\1\0"+
    "\1\265\2\0\1\266\72\0\1\267\6\0\1\245\1\246"+
    "\1\245\7\0\1\245\1\246\1\245\2\0\1\247\37\0"+
    "\1\151\1\0\1\151\2\0\1\270\6\0\1\153\1\262"+
    "\10\0\1\153\1\262\50\0\1\266\65\0\1\151\1\0"+
    "\1\151\2\0\1\266\6\0\1\153\11\0\1\153\51\0"+
    "\1\271\6\0\1\245\1\246\1\245\7\0\1\245\1\246"+
    "\1\245\2\0\1\247\37\0\1\151\1\0\1\151\2\0"+
    "\1\272\6\0\1\153\1\262\10\0\1\153\1\262\50\0"+
    "\1\273\6\0\1\245\1\274\10\0\1\245\1\274\3\0"+
    "\1\247\37\0\1\151\1\0\1\151\2\0\1\275\6\0"+
    "\1\153\1\262\10\0\1\153\1\262\50\0\1\276\6\0"+
    "\1\245\1\274\10\0\1\245\1\274\3\0\1\247\37\0"+
    "\1\277\1\0\1\277\2\0\1\300\65\0\1\151\1\0"+
    "\1\151\2\0\1\301\6\0\1\153\1\262\10\0\1\153"+
    "\1\262\50\0\1\302\6\0\1\245\1\274\10\0\1\245"+
    "\1\274\3\0\1\247\44\0\1\300\72\0\1\300\6\0"+
    "\1\245\11\0\1\245\4\0\1\247\37\0\1\151\1\0"+
    "\1\151\2\0\1\303\6\0\1\153\1\262\10\0\1\153"+
    "\1\262\50\0\1\304\6\0\1\245\1\274\10\0\1\245"+
    "\1\274\3\0\1\247\37\0\1\151\1\0\1\151\2\0"+
    "\1\305\6\0\1\153\1\262\10\0\1\153\1\262\50\0"+
    "\1\306\6\0\1\245\1\274\10\0\1\245\1\274\3\0"+
    "\1\247\37\0\1\151\1\0\1\151\11\0\1\153\1\262"+
    "\10\0\1\153\1\262\50\0\1\307\6\0\1\245\1\274"+
    "\10\0\1\245\1\274\3\0\1\247\44\0\1\310\6\0"+
    "\1\245\1\274\10\0\1\245\1\274\3\0\1\247\44\0"+
    "\1\311\6\0\1\245\1\274\10\0\1\245\1\274\3\0"+
    "\1\247\53\0\1\245\1\274\10\0\1\245\1\274\3\0"+
    "\1\247\20\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8909];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\1\1\0\1\11\2\0\7\11\2\1\2\11"+
    "\4\1\2\11\14\1\1\11\1\0\3\11\1\0\1\11"+
    "\2\0\1\1\1\0\1\11\1\0\4\11\25\1\2\11"+
    "\1\0\2\1\1\0\26\1\1\0\1\11\1\0\2\1"+
    "\1\0\26\1\1\0\1\1\1\0\17\1\1\0\11\1"+
    "\1\0\4\1\3\0\1\11\2\1\3\0\1\1\1\0"+
    "\1\1\1\0\1\1\2\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\2\0\1\1\3\0\1\1\1\0"+
    "\1\1\1\0\1\1\4\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[201];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

public Token actual;



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return new Token(ClaseLexica.EOF, yytext());
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignorar */
            }
          // fall through
          case 62: break;
          case 2:
            { System.out.println("Token encontrado: NOT (" + yytext() + ")"); return new Token(ClaseLexica.NOT, yytext());
            }
          // fall through
          case 63: break;
          case 3:
            { System.out.println("Token encontrado: MODULO (" + yytext() + ")"); return new Token(ClaseLexica.MODULO, yytext());
            }
          // fall through
          case 64: break;
          case 4:
            { System.out.println("Token encontrado: PARENTESIS_ABRE (" + yytext() + ")"); return new Token(ClaseLexica.PARENTESIS_ABRE, yytext());
            }
          // fall through
          case 65: break;
          case 5:
            { System.out.println("Token encontrado: PARENTESIS_CIERRA (" + yytext() + ")"); return new Token(ClaseLexica.PARENTESIS_CIERRA, yytext());
            }
          // fall through
          case 66: break;
          case 6:
            { System.out.println("Token encontrado: MULTIPLICACION (" + yytext() + ")"); return new Token(ClaseLexica.MULTIPLICACION, yytext());
            }
          // fall through
          case 67: break;
          case 7:
            { System.out.println("Token encontrado: MAS (" + yytext() + ")"); return new Token(ClaseLexica.MAS, yytext());
            }
          // fall through
          case 68: break;
          case 8:
            { System.out.println("Token encontrado: COMA (" + yytext() + ")"); return new Token(ClaseLexica.COMA, yytext());
            }
          // fall through
          case 69: break;
          case 9:
            { System.out.println("Token encontrado: MENOS (" + yytext() + ")"); return new Token(ClaseLexica.MENOS, yytext());
            }
          // fall through
          case 70: break;
          case 10:
            { System.out.println("Token encontrado: PUNTO (" + yytext() + ")"); return new Token(ClaseLexica.PUNTO, yytext());
            }
          // fall through
          case 71: break;
          case 11:
            { System.out.println("Token encontrado: DIVISION (" + yytext() + ")"); return new Token(ClaseLexica.DIVISION, yytext());
            }
          // fall through
          case 72: break;
          case 12:
            { System.out.println("Token encontrado: LITERAL_ENTERA (" + yytext() + ")");
    return new Token(ClaseLexica.LITERAL_ENTERA, yytext());
            }
          // fall through
          case 73: break;
          case 13:
            { System.out.println("Token encontrado: DOS_PUNTOS (" + yytext() + ")"); return new Token(ClaseLexica.DOS_PUNTOS, yytext());
            }
          // fall through
          case 74: break;
          case 14:
            { System.out.println("Token encontrado: PUNTO_Y_COMA (" + yytext() + ")"); return new Token(ClaseLexica.PUNTO_Y_COMA, yytext());
            }
          // fall through
          case 75: break;
          case 15:
            { System.out.println("Token encontrado: MENOR (" + yytext() + ")"); return new Token(ClaseLexica.MENOR, yytext());
            }
          // fall through
          case 76: break;
          case 16:
            { System.out.println("Token encontrado: ASIGNACION (" + yytext() + ")"); return new Token(ClaseLexica.ASIGNACION, yytext());
            }
          // fall through
          case 77: break;
          case 17:
            { System.out.println("Token encontrado: MAYOR (" + yytext() + ")"); return new Token(ClaseLexica.MAYOR, yytext());
            }
          // fall through
          case 78: break;
          case 18:
            { System.out.println("Token encontrado: ID (" + yytext() + ")");
    return new Token(ClaseLexica.ID, yytext());
            }
          // fall through
          case 79: break;
          case 19:
            { System.out.println("Token encontrado: CORCHETE_ABRE (" + yytext() + ")"); return new Token(ClaseLexica.CORCHETE_ABRE, yytext());
            }
          // fall through
          case 80: break;
          case 20:
            { System.out.println("Token encontrado: CORCHETE_CIERRA (" + yytext() + ")"); return new Token(ClaseLexica.CORCHETE_CIERRA, yytext());
            }
          // fall through
          case 81: break;
          case 21:
            { System.out.println("Token encontrado: LLAVE_ABRE (" + yytext() + ")"); return new Token(ClaseLexica.LLAVE_ABRE, yytext());
            }
          // fall through
          case 82: break;
          case 22:
            { System.out.println("Token encontrado: LLAVE_CIERRA (" + yytext() + ")"); return new Token(ClaseLexica.LLAVE_CIERRA, yytext());
            }
          // fall through
          case 83: break;
          case 23:
            { System.out.println("Token encontrado: DIFERENTE (" + yytext() + ")"); return new Token(ClaseLexica.DIFERENTE, yytext());
            }
          // fall through
          case 84: break;
          case 24:
            { System.out.println("Token encontrado: LITERAL_CADENA (" + yytext() + ")"); return new Token(ClaseLexica.LITERAL_CADENA, yytext());
            }
          // fall through
          case 85: break;
          case 25:
            { System.out.println("Token encontrado: AND (" + yytext() + ")"); return new Token(ClaseLexica.AND, yytext());
            }
          // fall through
          case 86: break;
          case 26:
            { System.out.println("Token encontrado: DIVISION_ENTERA (" + yytext() + ")"); return new Token(ClaseLexica.DIVISION_ENTERA, yytext());
            }
          // fall through
          case 87: break;
          case 27:
            { System.out.println("Token encontrado: LITERAL_DOUBLE (" + yytext() + ")");
    return new Token(ClaseLexica.LITERAL_DOUBLE, yytext());
            }
          // fall through
          case 88: break;
          case 28:
            { System.out.println("Token encontrado: LITERAL_FLOTANTE (" + yytext() + ")");
    return new Token(ClaseLexica.LITERAL_FLOTANTE, yytext());
            }
          // fall through
          case 89: break;
          case 29:
            { System.out.println("Token encontrado: MENOR_IGUAL (" + yytext() + ")"); return new Token(ClaseLexica.MENOR_IGUAL, yytext());
            }
          // fall through
          case 90: break;
          case 30:
            { System.out.println("Token encontrado: IGUAL (" + yytext() + ")"); return new Token(ClaseLexica.IGUAL, yytext());
            }
          // fall through
          case 91: break;
          case 31:
            { System.out.println("Token encontrado: MAYOR_IGUAL (" + yytext() + ")"); return new Token(ClaseLexica.MAYOR_IGUAL, yytext());
            }
          // fall through
          case 92: break;
          case 32:
            { System.out.println("Token encontrado: DO (" + yytext() + ")"); return new Token(ClaseLexica.DO, yytext());
            }
          // fall through
          case 93: break;
          case 33:
            { System.out.println("Token encontrado: IF (" + yytext() + ")"); return new Token(ClaseLexica.IF, yytext());
            }
          // fall through
          case 94: break;
          case 34:
            { System.out.println("Token encontrado: OR (" + yytext() + ")"); return new Token(ClaseLexica.OR, yytext());
            }
          // fall through
          case 95: break;
          case 35:
            { System.out.println("Token encontrado: LITERAL_RUNA (" + yytext() + ")");
    return new Token(ClaseLexica.LITERAL_RUNA, yytext());
            }
          // fall through
          case 96: break;
          case 36:
            { /* ignorar comentarios de una línea */
            }
          // fall through
          case 97: break;
          case 37:
            { System.out.println("Token encontrado: INT (" + yytext() + ")"); return new Token(ClaseLexica.INT, yytext());
            }
          // fall through
          case 98: break;
          case 38:
            { System.out.println("Token encontrado: PTR (" + yytext() + ")"); return new Token(ClaseLexica.PTR, yytext());
            }
          // fall through
          case 99: break;
          case 39:
            { /* ignorar comentarios de varias líneas */
            }
          // fall through
          case 100: break;
          case 40:
            { System.out.println("Token encontrado: CASE (" + yytext() + ")"); return new Token(ClaseLexica.CASE, yytext());
            }
          // fall through
          case 101: break;
          case 41:
            { System.out.println("Token encontrado: ELSE (" + yytext() + ")"); return new Token(ClaseLexica.ELSE, yytext());
            }
          // fall through
          case 102: break;
          case 42:
            { System.out.println("Token encontrado: FUNC (" + yytext() + ")"); return new Token(ClaseLexica.FUNC, yytext());
            }
          // fall through
          case 103: break;
          case 43:
            { System.out.println("Token encontrado: RUNE (" + yytext() + ")"); return new Token(ClaseLexica.RUNE, yytext());
            }
          // fall through
          case 104: break;
          case 44:
            { System.out.println("Token encontrado: SCAN (" + yytext() + ")"); return new Token(ClaseLexica.SCAN, yytext());
            }
          // fall through
          case 105: break;
          case 45:
            { System.out.println("Token encontrado: TRUE (" + yytext() + ")"); return new Token(ClaseLexica.TRUE, yytext());
            }
          // fall through
          case 106: break;
          case 46:
            { System.out.println("Token encontrado: VOID (" + yytext() + ")"); return new Token(ClaseLexica.VOID, yytext());
            }
          // fall through
          case 107: break;
          case 47:
            { System.out.println("Token encontrado: BREAK (" + yytext() + ")"); return new Token(ClaseLexica.BREAK, yytext());
            }
          // fall through
          case 108: break;
          case 48:
            { System.out.println("Token encontrado: FALSE (" + yytext() + ")"); return new Token(ClaseLexica.FALSE, yytext());
            }
          // fall through
          case 109: break;
          case 49:
            { System.out.println("Token encontrado: FLOAT (" + yytext() + ")"); return new Token(ClaseLexica.FLOAT, yytext());
            }
          // fall through
          case 110: break;
          case 50:
            { System.out.println("Token encontrado: PRINT (" + yytext() + ")"); return new Token(ClaseLexica.PRINT, yytext());
            }
          // fall through
          case 111: break;
          case 51:
            { System.out.println("Token encontrado: PROTO (" + yytext() + ")"); return new Token(ClaseLexica.PROTO, yytext());
            }
          // fall through
          case 112: break;
          case 52:
            { System.out.println("Token encontrado: WHILE (" + yytext() + ")"); return new Token(ClaseLexica.WHILE, yytext());
            }
          // fall through
          case 113: break;
          case 53:
            { System.out.println("Token encontrado: DOUBLE (" + yytext() + ")"); return new Token(ClaseLexica.DOUBLE, yytext());
            }
          // fall through
          case 114: break;
          case 54:
            { System.out.println("Token encontrado: RETURN (" + yytext() + ")"); return new Token(ClaseLexica.RETURN, yytext());
            }
          // fall through
          case 115: break;
          case 55:
            { System.out.println("Token encontrado: STRING (" + yytext() + ")"); return new Token(ClaseLexica.STRING, yytext());
            }
          // fall through
          case 116: break;
          case 56:
            { System.out.println("Token encontrado: STRUCT (" + yytext() + ")"); return new Token(ClaseLexica.STRUCT, yytext());
            }
          // fall through
          case 117: break;
          case 57:
            { System.out.println("Token encontrado: SWITCH (" + yytext() + ")"); return new Token(ClaseLexica.SWITCH, yytext());
            }
          // fall through
          case 118: break;
          case 58:
            { System.out.println("Token encontrado: COMPLEX (" + yytext() + ")"); return new Token(ClaseLexica.COMPLEX, yytext());
            }
          // fall through
          case 119: break;
          case 59:
            { System.out.println("Token encontrado: DEFAULT (" + yytext() + ")"); return new Token(ClaseLexica.DEFAULT, yytext());
            }
          // fall through
          case 120: break;
          case 60:
            { System.out.println("Token encontrado: LITERAL_COMPLEJA (" + yytext() + ")");
    return new Token(ClaseLexica.LITERAL_COMPLEJA, yytext());
            }
          // fall through
          case 121: break;
          case 61:
            { System.out.println("Token encontrado: PROGRAMA (" + yytext() + ")"); return new Token(ClaseLexica.PROGRAMA, yytext());
            }
          // fall through
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
